
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package edu.robertob.olc1.vj24.Analysis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RW_NEW = 56;
  public static final int RW_REMOVE = 58;
  public static final int UNIT_MINUS = 2;
  public static final int CHAR = 7;
  public static final int ASTERISK = 14;
  public static final int EQUALS = 11;
  public static final int SLASH = 15;
  public static final int DOUBLEEQUALS = 20;
  public static final int XOR = 50;
  public static final int RW_DOUBLE = 30;
  public static final int INTEGER = 5;
  public static final int GREATER = 22;
  public static final int RW_CHAR = 36;
  public static final int RW_FIND = 60;
  public static final int RW_DO = 44;
  public static final int LESS = 21;
  public static final int MINUS = 10;
  public static final int RW_BREAK = 42;
  public static final int OPENPAR = 26;
  public static final int RW_APPEND = 57;
  public static final int AND = 49;
  public static final int LESSEQUAL = 23;
  public static final int OR = 48;
  public static final int COMMA = 51;
  public static final int ENDLINE = 8;
  public static final int RW_WHILE = 41;
  public static final int PLUS = 9;
  public static final int DOT = 54;
  public static final int RW_RETURN = 47;
  public static final int ID = 4;
  public static final int CLOSEPAR = 27;
  public static final int RW_VAR = 40;
  public static final int RW_BOOL = 35;
  public static final int EOF = 0;
  public static final int DECIMAL = 6;
  public static final int RW_CONTINUE = 43;
  public static final int error = 1;
  public static final int NEGATION = 18;
  public static final int CLOSEBRACKET = 53;
  public static final int RW_FALSE = 34;
  public static final int MODULO = 16;
  public static final int RW_START_WITH = 46;
  public static final int RW_ROUND = 61;
  public static final int RW_PRINT = 28;
  public static final int RW_TRUE = 33;
  public static final int GREATEREQUAL = 24;
  public static final int COLON = 19;
  public static final int RW_IF = 32;
  public static final int RW_INT = 29;
  public static final int OPENBRACKET = 52;
  public static final int RW_VOID = 38;
  public static final int RW_CONST = 39;
  public static final int RW_FOR = 45;
  public static final int CLOSEBRACE = 13;
  public static final int NOT_EQUALS = 25;
  public static final int RW_STRING = 31;
  public static final int RW_ELSE = 37;
  public static final int OPENBRACE = 12;
  public static final int STRING = 3;
  public static final int DOUBLEASTERISK = 17;
  public static final int RW_LIST = 55;
  public static final int RW_LENGTH = 59;
  public static final int RW_TOSTRING = 62;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "UNIT_MINUS",
  "STRING",
  "ID",
  "INTEGER",
  "DECIMAL",
  "CHAR",
  "ENDLINE",
  "PLUS",
  "MINUS",
  "EQUALS",
  "OPENBRACE",
  "CLOSEBRACE",
  "ASTERISK",
  "SLASH",
  "MODULO",
  "DOUBLEASTERISK",
  "NEGATION",
  "COLON",
  "DOUBLEEQUALS",
  "LESS",
  "GREATER",
  "LESSEQUAL",
  "GREATEREQUAL",
  "NOT_EQUALS",
  "OPENPAR",
  "CLOSEPAR",
  "RW_PRINT",
  "RW_INT",
  "RW_DOUBLE",
  "RW_STRING",
  "RW_IF",
  "RW_TRUE",
  "RW_FALSE",
  "RW_BOOL",
  "RW_CHAR",
  "RW_ELSE",
  "RW_VOID",
  "RW_CONST",
  "RW_VAR",
  "RW_WHILE",
  "RW_BREAK",
  "RW_CONTINUE",
  "RW_DO",
  "RW_FOR",
  "RW_START_WITH",
  "RW_RETURN",
  "OR",
  "AND",
  "XOR",
  "COMMA",
  "OPENBRACKET",
  "CLOSEBRACKET",
  "DOT",
  "RW_LIST",
  "RW_NEW",
  "RW_APPEND",
  "RW_REMOVE",
  "RW_LENGTH",
  "RW_FIND",
  "RW_ROUND",
  "RW_TOSTRING"
  };
}

